language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-restapi' ]; then cd .. && eval "mv $currentfolder generator-restapi" && cd generator-restapi; fi
